# API Contract: Timeline-Scoped Events Endpoints
# Feature: 001-multi-timeline-system
# Version: 1.0.0
# Note: These replace the existing /api/events endpoints

openapi: 3.0.3
info:
  title: Timeline-Scoped Events API
  version: 1.0.0

paths:
  /api/timelines/{timelineId}/events:
    parameters:
      - $ref: '#/components/parameters/timelineId'

    get:
      summary: List events in timeline
      description: Returns events within the specified timeline
      tags: [Events]
      security:
        - bearerAuth: []
      parameters:
        - name: startDate
          in: query
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          schema:
            type: string
            format: date
        - name: status
          in: query
          schema:
            type: string
            enum: ['Not Started', 'In Progress', 'Completed']
        - name: priority
          in: query
          schema:
            type: string
            enum: [High, Medium, Low]
        - name: categoryId
          in: query
          schema:
            type: string
            format: uuid
        - name: outcomeTag
          in: query
          schema:
            type: string
            enum: ['Went Well', 'Needs Improvement', 'Failed']
          description: Filter by retrospective outcome (Completed/Archived timelines only)
        - name: sortBy
          in: query
          schema:
            type: string
            enum: [date, priority, status, title, updatedAt]
            default: date
        - name: sortOrder
          in: query
          schema:
            type: string
            enum: [asc, desc]
            default: asc
      responses:
        '200':
          description: List of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventWithCategory'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

    post:
      summary: Create event
      description: Editor+ role required
      tags: [Events]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEvent'
      responses:
        '201':
          description: Event created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Requires Editor role or timeline is read-only (archived)

  /api/timelines/{timelineId}/events/{eventId}:
    parameters:
      - $ref: '#/components/parameters/timelineId'
      - name: eventId
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      summary: Get event details
      tags: [Events]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Event details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventWithCategory'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: Update event
      description: Editor+ role required. Retrospective fields editable only on Completed/Archived timelines.
      tags: [Events]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEvent'
      responses:
        '200':
          description: Event updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Requires Editor role or timeline is read-only
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          description: Conflict - event was modified by another user

    delete:
      summary: Delete event
      description: Editor+ role required
      tags: [Events]
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Event deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Requires Editor role or timeline is read-only
        '404':
          $ref: '#/components/responses/NotFound'

  /api/timelines/{timelineId}/events/{eventId}/duplicate:
    parameters:
      - $ref: '#/components/parameters/timelineId'
      - name: eventId
        in: path
        required: true
        schema:
          type: string
          format: uuid

    post:
      summary: Duplicate event
      description: Create a copy of the event with optional modifications
      tags: [Events]
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Override title (default: "Copy of {original}")
                date:
                  type: string
                  format: date
                  description: Override date (default: same as original)
      responses:
        '201':
          description: Duplicate created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Requires Editor role
        '404':
          $ref: '#/components/responses/NotFound'

  /api/timelines/{timelineId}/events/bulk-status:
    parameters:
      - $ref: '#/components/parameters/timelineId'

    put:
      summary: Bulk update event status
      description: Update status for multiple events at once
      tags: [Events]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eventIds:
                  type: array
                  items:
                    type: string
                    format: uuid
                  minItems: 1
                  maxItems: 100
                status:
                  type: string
                  enum: ['Not Started', 'In Progress', 'Completed']
              required: [eventIds, status]
      responses:
        '200':
          description: Bulk update result
          content:
            application/json:
              schema:
                type: object
                properties:
                  updated:
                    type: integer
                  failed:
                    type: integer
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        eventId:
                          type: string
                        error:
                          type: string
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Requires Editor role

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    timelineId:
      name: timelineId
      in: path
      required: true
      schema:
        type: string
        format: uuid

  schemas:
    Event:
      type: object
      properties:
        id:
          type: string
          format: uuid
        timelineId:
          type: string
          format: uuid
        title:
          type: string
          maxLength: 255
        date:
          type: string
          format: date
        time:
          type: string
          pattern: '^([01]?[0-9]|2[0-3]):[0-5][0-9]$'
          nullable: true
        endTime:
          type: string
          pattern: '^([01]?[0-9]|2[0-3]):[0-5][0-9]$'
          nullable: true
        description:
          type: string
          nullable: true
        categoryId:
          type: string
          format: uuid
        assignedPerson:
          type: string
          nullable: true
        status:
          type: string
          enum: ['Not Started', 'In Progress', 'Completed']
        priority:
          type: string
          enum: [High, Medium, Low]
        retroNotes:
          type: string
          nullable: true
          description: Only editable when timeline is Completed or Archived
        outcomeTag:
          type: string
          enum: ['Went Well', 'Needs Improvement', 'Failed']
          nullable: true
        sourceEventId:
          type: string
          format: uuid
          nullable: true
          description: Original event if this was copied
        createdBy:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required: [id, timelineId, title, date, categoryId, status, priority, createdBy, createdAt, updatedAt]

    EventWithCategory:
      allOf:
        - $ref: '#/components/schemas/Event'
        - type: object
          properties:
            category:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                name:
                  type: string
                color:
                  type: string
              required: [id, name, color]
          required: [category]

    CreateEvent:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
        date:
          type: string
          format: date
        time:
          type: string
          pattern: '^([01]?[0-9]|2[0-3]):[0-5][0-9]$'
        endTime:
          type: string
          pattern: '^([01]?[0-9]|2[0-3]):[0-5][0-9]$'
        description:
          type: string
        categoryId:
          type: string
          format: uuid
        assignedPerson:
          type: string
        status:
          type: string
          enum: ['Not Started', 'In Progress', 'Completed']
          default: 'Not Started'
        priority:
          type: string
          enum: [High, Medium, Low]
          default: Medium
      required: [title, date, categoryId]

    UpdateEvent:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
        date:
          type: string
          format: date
        time:
          type: string
          pattern: '^([01]?[0-9]|2[0-3]):[0-5][0-9]$'
          nullable: true
        endTime:
          type: string
          pattern: '^([01]?[0-9]|2[0-3]):[0-5][0-9]$'
          nullable: true
        description:
          type: string
          nullable: true
        categoryId:
          type: string
          format: uuid
        assignedPerson:
          type: string
          nullable: true
        status:
          type: string
          enum: ['Not Started', 'In Progress', 'Completed']
        priority:
          type: string
          enum: [High, Medium, Low]
        retroNotes:
          type: string
          nullable: true
        outcomeTag:
          type: string
          enum: ['Went Well', 'Needs Improvement', 'Failed']
          nullable: true

  responses:
    Unauthorized:
      description: Missing or invalid authentication
    Forbidden:
      description: Insufficient permissions
    NotFound:
      description: Resource not found
    ValidationError:
      description: Invalid input
